version: '3.9'

services:
  php:
    build:
      context: php
      args:
        TIMEZONE: ${TIMEZONE}
    env_file:
      - ./.env
    volumes:
      - .:/var/www/ecmvela:rw
    ports:
      - "8083:80"
    links:
      - db
    command:
      - "bash"
      - "-c"
      - "rm -rf /var/www/ecmvela/var/cache \
        && set -eux && mkdir -p /var/www/ecmvela/var/logs
        && mkdir -p /var/www/ecmvela/var/cache \
        && mkdir -p /var/www/ecmvela/var/translations \
        && chmod -R 777 /var/www/ecmvela/var \
        && apachectl -D FOREGROUND
        "
  db:
    image: mariadb:latest
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql:rw
    restart: always
    ports:
      - "3303:3306"
volumes:
  db-data: {}