version: '3.9'

services:
  php:
    build:
      context: docker
    env_file:
      - ./.env
    volumes:
      - .:/var/www/mip-workshop:rw
    ports:
      - "8083:80"
    command:
      - "bash"
      - "-c"
      - "apachectl -D FOREGROUND"